#!/usr/bin/env python3
"""Generate Verilator PMU snapshot copy statements from RTL parameters.

The with-cache RTL exposes PMU counters as flattened top-level ports whose names
include the SM index. This script keeps the C++ sampling code synchronized with
the Chisel-exported num_sm parameter instead of hard-coding the number of SMs in
hand-written C++.
"""

import json
import sys
from pathlib import Path

PIPELINE_FIELDS = (
    ("active_cycles", "activeCycles"),
    ("total_scalar_issued", "totalScalarIssued"),
    ("total_vector_issued", "totalVectorIssued"),
    ("exec_structural_hazard_cycles_x", "execStructuralHazardCyclesX"),
    ("exec_structural_hazard_cycles_v", "execStructuralHazardCyclesV"),
    ("data_dep_stall_cycles", "dataDepStallCycles"),
    ("barrier_stall_cycles", "barrierStallCycles"),
    ("control_hazard_flush_count", "controlHazardFlushCount"),
    ("frontend_stall_cycles", "frontendStallCycles"),
    ("lsu_backpressure_cycles", "lsuBackpressureCycles"),
    ("ibuffer_full_cycles", "ibufferFullCycles"),
)

INST_CLASS_FIELDS = (
    ("compute_issued", "computeIssued"),
    ("mem_issued", "memIssued"),
    ("ctrl_issued", "ctrlIssued"),
)

DCACHE_FIELDS = (
    ("total_req", "totalReq"),
    ("read_req", "readReq"),
    ("write_req", "writeReq"),
    ("read_miss", "readMiss"),
    ("write_miss", "writeMiss"),
    ("read_primary_miss", "readPrimaryMiss"),
    ("read_secondary_miss", "readSecondaryMiss"),
    ("read_primary_full_miss", "readPrimaryFullMiss"),
    ("read_secondary_full_miss", "readSecondaryFullMiss"),
    ("write_fresh_miss", "writeFreshMiss"),
    ("write_inflight_miss", "writeInflightMiss"),
    ("replacements", "replacements"),
    ("dirty_writebacks", "dirtyWritebacks"),
    ("mshr_full_cycles", "mshrFullCycles"),
    ("rtab_replays", "rtabReplays"),
    ("bank_conflict_cycles", "bankConflictCycles"),
    ("core_req_pipe_pipelined_cycles", "coreReqPipePipelinedCycles"),
    ("mem_rsp_pipe_decoupled_cycles", "memRspPipeDecoupledCycles"),
)


def parameter_u32(parameters: dict, name: str) -> int:
    value = parameters.get(name)
    if not isinstance(value, int) or value < 0:
        raise ValueError(f"RTL parameter {name} is missing or invalid")
    return value


def emit_sm_copy(sm: int) -> list[str]:
    lines = [
        f"    {{",
        f"        auto& dst = pmu_snapshot.pipeline[{sm}];",
    ]
    for dst, src in PIPELINE_FIELDS:
        lines.append(f"        dst.{dst} = dut->io_pmu_pipeline_{sm}_{src};")
    lines.extend([
        f"    }}",
        f"    {{",
        f"        auto& dst = pmu_snapshot.inst_class[{sm}];",
    ])
    for dst, src in INST_CLASS_FIELDS:
        lines.append(f"        dst.{dst} = dut->io_pmu_instClass_{sm}_{src};")
    lines.extend([
        f"    }}",
        f"    {{",
        f"        auto& dst = pmu_snapshot.dcache[{sm}];",
    ])
    for dst, src in DCACHE_FIELDS:
        lines.append(f"        dst.{dst} = dut->io_pmu_dcache_{sm}_{src};")
    lines.append(f"    }}")
    return lines


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: gen_pmu_snapshot_inc.py parameters.json output.inc", file=sys.stderr)
        return 2

    params_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    parameters = json.loads(params_path.read_text(encoding="utf-8"))
    num_sm = parameter_u32(parameters, "num_sm")

    lines = [
        "// Generated by gen_pmu_snapshot_inc.py; do not edit by hand.",
        f"static constexpr uint32_t GENERATED_PMU_NUM_SM = {num_sm};",
        "",
        "void ventus_rtlsim_t::copy_pmu_counters_from_dut() {",
    ]
    for sm in range(num_sm):
        lines.extend(emit_sm_copy(sm))
    lines.append("}")
    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
